# Generated by Django 5.2.4 on 2025-08-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_sala_atualizada_em_alter_sala_criador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_por', models.ManyToManyField(blank=True, related_name='aulas_concluidas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='usuarios.sala')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.FloatField(default=0.0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='usuarios.sala')),
            ],
            options={
                'unique_together': {('aluno', 'sala')},
            },
        ),
    ]
