# Generated by Django 5.2.8 on 2025-12-22 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0017_titulo_usuario_foto_participacaosala_titulos_sala_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Módulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('missoes', models.ManyToManyField(blank=True, help_text='Missões que fazem parte deste módulo', to='usuarios.missao', verbose_name='Missões Relacionadas')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConteudoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('texto', 'Texto/Artigo'), ('video', 'Vídeo'), ('arquivo', 'Arquivo/PDF'), ('link', 'Link Externo')], max_length=10, verbose_name='Tipo de Conteúdo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('conteudo', models.TextField(blank=True, help_text="Usado para tipo 'texto'", verbose_name='Conteúdo de Texto')),
                ('arquivo', models.FileField(blank=True, help_text="Usado para tipo 'arquivo' ou 'video'", null=True, upload_to='conteudos/', verbose_name='Arquivo')),
                ('link', models.URLField(blank=True, help_text="Usado para tipo 'link' ou 'video' (YouTube, etc)", verbose_name='Link Externo')),
                ('duracao_estimada', models.IntegerField(default=0, help_text='Tempo estimado para completar este conteúdo', verbose_name='Duração Estimada (minutos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='cursos.modulo')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Trilha')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('pontos_necessarios', models.IntegerField(default=0, help_text='Pontos totais que o aluno precisa ter para acessar', verbose_name='Pontos Necessários')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='usuarios.sala')),
                ('trilha_anterior', models.ForeignKey(blank=True, help_text='Trilha que deve ser completada antes desta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.trilha', verbose_name='Trilha Anterior')),
            ],
            options={
                'verbose_name': 'Trilha de Aprendizado',
                'verbose_name_plural': 'Trilhas de Aprendizado',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.trilha'),
        ),
        migrations.CreateModel(
            name='VisualizacaoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('completo', models.BooleanField(default=False, verbose_name='Marcado como Completo')),
                ('tempo_gasto_segundos', models.IntegerField(blank=True, default=0)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.conteudomodulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de Conteúdo',
                'verbose_name_plural': 'Visualizações de Conteúdos',
                'ordering': ['-data_visualizacao'],
                'unique_together': {('usuario', 'conteudo')},
            },
        ),
        migrations.AddField(
            model_name='conteudomodulo',
            name='visualizado_por',
            field=models.ManyToManyField(blank=True, related_name='conteudos_visualizados', through='cursos.VisualizacaoConteudo', to=settings.AUTH_USER_MODEL),
        ),
    ]
