# Generated by Django 5.2.8 on 2026-01-17 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_modulo_conteudomodulo_trilha_modulo_trilha_and_more'),
        ('usuarios', '0017_titulo_usuario_foto_participacaosala_titulos_sala_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trilha',
            options={'ordering': ['ordem'], 'verbose_name': 'Trilha', 'verbose_name_plural': 'Trilhas'},
        ),
        migrations.AlterUniqueTogether(
            name='trilha',
            unique_together={('sala', 'nome')},
        ),
        migrations.AddField(
            model_name='trilha',
            name='professor',
            field=models.ForeignKey(help_text='Professor que criou e gerencia esta trilha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trilhas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='pontos_necessarios',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='trilha_anterior',
        ),
    ]
