# Generated by Django 5.2.8 on 2026-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_trilha_options_alter_trilha_unique_together_and_more'),
        ('usuarios', '0017_titulo_usuario_foto_participacaosala_titulos_sala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='missoes',
            field=models.ManyToManyField(blank=True, help_text='Selecione quais missões desta sala contam para o progresso da trilha', related_name='trilhas', to='usuarios.missao', verbose_name='Missões da Trilha'),
        ),
    ]
