# Generated by Django 5.2.8 on 2026-01-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_trilha_missoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='missoes',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='missoes',
        ),
    ]
