# Generated by Django 5.2.4 on 2025-08-26 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sala',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
