# Generated by Django 5.2.4 on 2025-08-29 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_sala_atualizada_em_alter_sala_criador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='salas_participando', to=settings.AUTH_USER_MODEL),
        ),
    ]
