# Generated by Django 5.2.4 on 2025-08-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_sala_alunos'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
