# Generated by Django 5.2.4 on 2025-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tipo_usuario_criador',
            field=models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=10),
        ),
    ]
