# Generated by Django 5.2.4 on 2025-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_mensagem_missao_mensagemmissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='pontos_atingidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('corrigida', 'corrigida')], default='pendente', max_length=20),
        ),
    ]
