# Generated by Django 5.2.4 on 2025-11-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_missao_pontos_atingidos_missao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pontos_na_sala',
            field=models.IntegerField(default=0, verbose_name='pontos na sala'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pontos_totais',
            field=models.IntegerField(default=0, verbose_name='pontos totais'),
        ),
    ]
