# Generated by Django 5.2.4 on 2025-11-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_pontos_na_sala_usuario_pontos_totais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pontos_na_sala',
        ),
    ]
