# Generated by Django 5.0.6 on 2025-11-19 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_usuario_pontos_na_sala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemmissao',
            options={'ordering': ['data_envio'], 'verbose_name': 'Mensagem da Missão', 'verbose_name_plural': 'Mensagens das Missões'},
        ),
        migrations.AlterModelOptions(
            name='missao',
            options={'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='missao',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='tipo_usuario_criador',
        ),
        migrations.AddField(
            model_name='sala',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='mensagemmissao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='missao',
            name='pontos_atingidos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='missao',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes', to='usuarios.sala'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('corrigida', 'Corrigida')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pontos_totais',
            field=models.IntegerField(default=0, verbose_name='Pontos Totais'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('admin', 'Admin')], default='aluno', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.CreateModel(
            name='ParticipacaoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_na_sala', models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=10)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='usuarios.sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participação na Sala',
                'verbose_name_plural': 'Participações nas Salas',
                'unique_together': {('usuario', 'sala')},
            },
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
