# Generated by Django 5.2.8 on 2025-12-04 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_mensagemmissao_options_alter_missao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemmissao',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentário'), ('entrega', 'Entrega'), ('correcao', 'Correção')], default='comentario', max_length=10),
        ),
        migrations.CreateModel(
            name='correcaoMissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_atingidos', models.IntegerField()),
                ('data_correcao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcoes', to='usuarios.missao')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correção da Missão',
                'verbose_name_plural': 'Correções das Missões',
                'unique_together': {('missao', 'aluno')},
            },
        ),
    ]
