# Generated by Django 5.2.8 on 2025-12-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoMissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_missoes/')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='usuarios.missao')),
            ],
            options={
                'verbose_name': 'Anexo da Missão',
                'verbose_name_plural': 'Anexos das Missões',
            },
        ),
    ]
