# Generated by Django 5.2.8 on 2025-12-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_anexomissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexomissao',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
