# Generated by Django 5.2.8 on 2025-12-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_anexomissao_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('global', 'Global'), ('sala', 'Sala')], default='global', max_length=10, verbose_name='Tipo')),
                ('pontos_necessarios', models.IntegerField(default=0, verbose_name='Pontos Necessários')),
                ('missoes_necessarias', models.IntegerField(default=0, verbose_name='Missões Completadas Necessárias')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='titulos/', verbose_name='Ícone do Título')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='participacaosala',
            name='titulos_sala',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'sala'}, related_name='participacoes_com_titulo', to='usuarios.titulo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='titulos_globais',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'global'}, related_name='usuarios_com_titulo', to='usuarios.titulo'),
        ),
    ]
