# Generated by Django 5.2.8 on 2026-01-22 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_modulo_missoes_remove_trilha_missoes'),
        ('usuarios', '0017_titulo_usuario_foto_participacaosala_titulos_sala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missoes', to='cursos.modulo'),
        ),
        migrations.AddField(
            model_name='missao',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missoes', to='cursos.trilha'),
        ),
    ]
